### ISSUE TITLE
Bot issue ? Or Help

### ISSUE THREAD

**Issue by Laki1370** [woosal1337/Chegg#4]
Hello, Thank you so much for coming up with something so great, and so useful to everyone who is unable to pay for Chegg. I followed Your tutorial exactly as you did it, I tried it 4 times. I managed to get ...

" Committing...
Running Setup...
Setup Completed!
Running bot...
BOT has been CONNECTED!
Committing... " 

and the next step in the video was to go back to our discord server and write " +mail " after that the bot should be able to respond. Whereas in my case, I never received a response from the bot. 

It seemed like the Visual Studio Code has some issues, so decided to run the whole thing in Atom. And still, the bot doesn't respond to " +email ". 

I noticed that in Visual Studio Code I got some problems which I don't understand why I got them since you didn't.  I will upload a picture of the problems.

If you could please help me out, that would be absolutely great. Thank You so much 

![Screenshot 2021-03-03 235700](https://user-images.githubusercontent.com/80022199/109913563-3c09db80-7c7c-11eb-9dcd-546507794c7e.jpg)

**Comment by woosal1337** [comment]
If it says it is committing, that means it is working.
